[database]
engine = "postgresql"
name = "dprompts"
user = "rtp"
password = "password"
host = "localhost"
port = "5432"

[llm]
api-endpoint = "http://localhost:11434/api/chat"
model = "gemma2:2b"
temperature = 0.7
topP = 0.9